### ISSUE TITLE
What is the purpose of the `network_role_id` field in the `subnets` table?

### ISSUE THREAD

**Issue by chuhn** [opennetadmin/ona#95] opened 2015-12-11 11:48 UTC
Just stumbled upon this during DB migration. It is NULL in our old DB but has a NOTNULL constraint in the current version.
Seems to be used nowhere though.

**Comment by mattpascoe** [comment] 2015-12-14 21:27
Short answer, is it is old junk that is not used.. really the subnet_type_id amounts to what it was intended to be.  I should probably just drop that out entirely.

What I suspect you are running into is issue #86.  I have fixes for it in the miradbfix branch if you would like to try that out.  I need to get that dang thing merged in before it causes people too much grief.  Any help in testing that would be appreciated.

**Comment by mattpascoe** [comment] 2018-01-03 17:56
This column is now removed in the latest version.. closing ticket.

**Closed by mattpascoe** 2018-01-03 17:56 UTC
Labels: Question
