### ISSUE TITLE
mysql 8 and table "groups"

### ISSUE THREAD

**Issue by norge-ice** [opennetadmin/ona#156] opened 2020-04-10 10:37 UTC
is impossible to create a table with name "groups" in mysql 8, during installation, because is a Reserved Words( https://dev.mysql.com/doc/refman/8.0/en/keywords.html )

**Comment by mattpascoe** [comment] 2020-04-12 23:52
I am aware of this. I have started work to make the adjustments for this.  Please try the development branch as it should address this issue.  Thank you.

**Comment by mattpascoe** [comment] 2020-04-24 23:14
closing as a dupe of #150

**Closed by mattpascoe** 2020-04-24 23:14 UTC
Labels: Bug
